# Configuration for ensemble model
threshold: 0.5  # Threshold for binary prediction

# Models to ensemble
models:
  - name: "unet_scratch"
    predictions_dir: "outputs/unet_s/predictions/best"
    data_dir: "data/interim"
    
  - name: "unet_resnet34"
    predictions_dir: "outputs/unet_tl/predictions/best"
    data_dir: "data/interim"

# Weights for ensemble (optional, default is equal weighting)
weights: [1.0, 1.0] 