# Configuration for U-Net from scratch (small architecture)
seed: 42
output_dir: "outputs"
batch_size: 16  # Increased batch size slightly
epochs: 100
num_workers: 4
patience: 15  # Early stopping patience

# Data configuration
data:
  raw_dir: "data/raw"
  interim_dir: "data/interim"
  split_csv: "data/splits/splits.csv"

# Model configuration
model:
  type: "unet_scratch"
  in_channels: 1  # Explicitly using 1 channel for grayscale
  n_classes: 1
  bilinear: true

# Loss function
loss:
  type: "bce_dice"  # Combination of BCE and Dice loss

# Optimizer
optimizer:
  type: "adam"
  lr: 0.0001  # Increased learning rate
  weight_decay: 0.00005  # Reduced weight decay to moderate level

# Learning rate scheduler
scheduler:
  type: "plateau"
  factor: 0.5
  patience: 10 