# Configuration for U-Net from scratch
seed: 42
output_dir: "outputs"
batch_size: 16
epochs: 100
num_workers: 4

# Data configuration
data:
  raw_dir: "data/raw"
  interim_dir: "data/interim"
  split_csv: "data/splits/splits.csv"

# Model configuration
model:
  type: "unet_scratch"
  in_channels: 1
  n_classes: 1
  bilinear: true

# Loss function
loss:
  type: "bce_dice"  # Combination of BCE and Dice loss

# Optimizer
optimizer:
  type: "adam"
  lr: 0.0001
  weight_decay: 0.00001

# Learning rate scheduler
scheduler:
  type: "plateau"
  factor: 0.5
  patience: 10 