# Configuration for U-Net with ResNet-34 transfer learning
seed: 42
output_dir: "outputs"
batch_size: 8  # Smaller batch size due to larger model
epochs: 100
num_workers: 4

# Data configuration
data:
  raw_dir: "data/raw"
  interim_dir: "data/interim"
  split_csv: "data/splits/splits.csv"

# Model configuration
model:
  type: "unet_resnet34"
  in_channels: 3  # ResNet-34 expects 3 channels
  n_classes: 1
  pretrained: true
  freeze_epochs: 10  # Freeze encoder for first 10 epochs

# Loss function
loss:
  type: "bce_dice"  # Combination of BCE and Dice loss

# Optimizer
optimizer:
  type: "adam"
  lr: 0.0001
  weight_decay: 0.00001

# Learning rate scheduler
scheduler:
  type: "plateau"
  factor: 0.2
  patience: 8 